version: '3.8'

# Multi-Tenant Inventory Management System
# Each tenant has completely isolated data
services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory-backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/inventory?sslmode=disable
      JWT_SECRET: change-me-in-production
      PORT: 8080
      ENVIRONMENT: production
      CORS_ORIGINS: http://localhost
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - inventory-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - inventory-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  inventory-network:
    driver: bridge